=pod

=head1 NAME

App::BumpVersion - A tool to rewrite or bump your Perl module versions

=head1 SYNOPSIS

 use App::BumpVersion;
 my $app = App::BumpVersion->new;
 
 # Options
 $app->verbose(1)->follow_symlinks(0);
 
 # Bump versions for modules in current dist directory
 $app->bump_versions;
 
 # Bump versions in specified dist directory
 $app->bump_versions(dir => 'Foo-Bar/');
 
 # Override module to read version from
 $app->bump_versions(version_from => 'lib/Foo/Bar.pm');
 
 # Don't bump, just synchronize versions with main module
 $app->bump_versions(bump => 0);
 
 # Set versions to specified version (or use the V environment variable)
 $app->bump_versions(bump => sub { '0.56' });
 
 # Custom version bump algorithm
 $app->bump_versions(bump => sub { shift + 0.05 });
 
=head1 DESCRIPTION

L<App::BumpVersion> is a tool for managing Perl module versions in a
distribution. It is heavily based on the L<Dist::Zilla> plugin
L<Dist::Zilla::Plugin::RewriteVersion>. Similarly to that plugin, the C<V>
environment variable can be used to override the version that is set, but note
that in this case, it overrides the version-bumping functionality altogether.
Existing version assignments and new versions must be parseable with the same
rules as in L<Dist::Zilla::Plugin::RewriteVersion/"DESCRIPTION">.

See L<perl-bump-version> for details on command-line usage.

=head1 ATTRIBUTES

=head2 allow_decimal_underscore

 my $bool = $app->allow_decimal_underscore
 $app = $app->allow_decimal_underscore(1);

If true, decimal versions with underscores will be allowed. Defaults to false.
As with L<Dist::Zilla::Plugin::RewriteVersion>, version tuples with underscores
are never allowed.

=head2 follow_symlinks

 my $bool = $app->follow_symlinks;
 $app = $app->follow_symlinks(1);

If true, the application will follow symlinked directories when traversing the
distribution for modules. Defaults to false.

=head2 global

 my $bool = $app->global;
 $app = $app->global(1);

If true, the application will replace all version assignments found in each
particular module instead of just the first instance found. Defaults to false.

=head2 verbose

 my $bool = $app->verbose;
 $app = $app->verbose(1);

Enable progress messages to be printed to STDOUT. Defaults to false.

=head1 METHODS

=head2 new

 my $app = App::BumpVersion->new;

Construct a new L<App::BumpVersion> object.

=head2 bump_versions

 $app = $app->bump_versions;
 $app = $app->bump_versions(dir => '/foo/projects/Acme-Bar');
 $app = $app->bump_versions(bump => sub { 'v5.0.1' });
 $app = $app->bump_versions(version_from => 'lib/My/Module.pm');
 $app = $app->bump_versions(is_trial => 1);

Rewrites versions in all perl files found that contain a version assignment in
the form C<our $VERSION = '...'>. See L<Dist::Zilla::Plugin::RewriteVersion>
for more information on the version parsing semantics. Accepts the following
options:

=over

=item * bump

If set to a code reference, it will be called with the current version as a
string, and will be expected to return the new version to use for rewriting.
Otherwise, a true value will use L<Version::Next> to determine the version to
set, and a false value will use the original unchanged version. Defaults to
true.

=item * dir

Relative or absolute path for the distribution directory to operate on.
Defaults to the current working directory.

=item * is_trial

If true, C<# TRIAL> will be appended to the version assignment line. Defaults
to false.

=item * version_from

File to read version from before bumping (if applicable), relative to the
distribution root directory. If unset, the main module filename will be guessed
from the distribution directory name, using heuristics similar to
L<Dist::Zilla::Plugin::NameFromDirectory> and L<Dist::Zilla/"main_module">.

=back

=head2 rewrite_version

 my $bool = $app->rewrite_version($path, $version, $is_trial);

Rewrites the version of the file at C<$path> to C<$version>. C<$path> may be a
L<Path::Tiny> object. Returns true if the version was rewritten, or false if no
version assignment was found.

=head2 rewrite_versions

 $app = $app->rewrite_versions($dir, $version, $is_trial);

Rewrites the versions of all perl files found in C<$dir> to C<$version> using
L</"rewrite_version">.

=head2 version_from

 my $version = $app->version_from($path);

Attempts to read version from the file at C<$path>. Returns C<undef> if no
version assignment was found.

=head1 BUGS

Report any issues on the public bugtracker.

=head1 AUTHOR

Dan Book <dbook@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is Copyright (c) 2015 by Dan Book.

This is free software, licensed under:

  The Artistic License 2.0 (GPL Compatible)

=head1 SEE ALSO

L<Dist::Zilla::Plugin::RewriteVersion>, L<Version::Next>

=cut
